Sacrifice victims now receive a custom "Mansus" phobia.
lizardqueenlexi/orbstation pull request #316
Opened 2022-11-23 05:51 UTC by lizardqueenlexi

## About The Pull Request

Added a new phobia, "the mansus". This phobia is similar to the "supernatural" phobia, but with a more narrowed focus - causing fear of all heretic items and summons, as well as the Mansus Grasp spell itself, plus a few cult items (I figure the layman can't really tell the difference). This phobia cannot be randomly gained or selected with the Phobia quirk, and is given permanently to sacrifice targets in place of the "supernatural" phobia currently given.

For fun, this phobia has unique text when gained/lost, as well as randomly-selected glitch/error text upon medical scanning.

## Why It's Good For The Game

I think it's a bit silly that getting sacrificed by a heretic makes you suddenly start screaming and freaking out because you saw a wizard hat. I think it's potentially game-ruining for a chaplain to start constantly screaming at their own jumpsuit and weapon. Making a custom, more focused phobia preserves the effect of "people who are sacrificed have a harder time fighting the heretic afterward" without all the baggage that comes with the supernatural phobia.

The idea has been tossed around to replace this phobia with a more custom sort of "curse" that accomplishes the same effect in a more mechanically interesting and flavorful way, and I may try to put something together to that effect in the future. For now, though, I think this is a good stopgap.

## Changelog

:cl:
add: Added a new "mansus" phobia given permanently to sacrifice victims.
/:cl:

2022-11-23 06:19 UTC, VioletN approved these changes

2022-11-23 09:04 UTC, Profakos requested changes
Runtime errors because you have not added regex entries to https://github.com/lizardqueenlexi/orbstation/blob/master/strings/phobia.json . Hopefully an empty array would solve the runtime. Please do this for the other phobias too that had their json entries removed, they runtime a lot during CI.

Update: it always runtimes when there are no words, looks like it. Maybe make it return instead of runtime when there is no entry, though that will require further changes...

2022-11-23 09:17 UTC, Profakos commented
Update: it always runtimes when there are no words, looks like it. Maybe make it return instead of runtime when there is no entry, though that will require further changes...

2022-11-24 02:20 UTC, flowercuco commented
i wonder why 
/mob/living/simple_animal/hostile/heretic_summon
isnt in the supernatural phobia...
a fucked up flesh monster = not scary :smile:
that same flesh monster holding a knife = AHHHHHHHH FUCK!!!!!!!!!!!!!!!!!!!

ill see from the pr if anyone asked about it ig, if it isnt in the supernatural phobia it isnt like, a huge deal i think

2022-11-24 20:33 UTC, Jacquerel commented
I'm happy to approve this only it would be nice to do something for the other phobias which occasionally call CI failures while you're touching that file 😅

2022-11-24 21:24 UTC, Jacquerel approved these changes

2022-11-24 21:34 UTC, Profakos approved these changes

2022-11-24 21:35 UTC, Profakos commented
Approved, as the heretic issue is fixened.

2022-11-24 23:54 UTC, merged