Disabled three potentially dysphoria-causing disease symptoms.
lizardqueenlexi/orbstation pull request #320
Opened 2022-11-25 07:58 UTC by lizardqueenlexi

I've disabled three advanced virus symptoms that I thought likely to cause dysphoria. They are: "beard" (forces your character to grow a beard), "shedding" (makes your character's hair fall out), and "voice change" (makes your character's voice change, causing their name to be randomized in chat).

I'm not certain what impact removing three options may have on things like sentient virus and virology in general, but also, I feel any possible impact is worth _not_ having things that don't do much other than make people uncomfortable in the game. Worst case, we come up with new symptoms later to add in to replace these.

2022-11-25 08:20 UTC, SeigaSeiga commented
Mechanical considerations, these aren't arguments against doing this but a basic summary of what impacts the symptoms had on viruses.

- Beard is what you'd call a 'buffing' symptom. It boosts most of the important positive stats of a virus [except stealth] in addition to its stated effect. There's very few of these types of symptom, most of them are the 'chat spam' symptoms.
- Same goes for Alopecia, the shedding symptom, though it's not as numerically potent as a supporting symptom as beard.
- Voice change is very much a symptom taken for its effect of causing radio confusion. It doesn't really have a role in supporting other symptoms, so it's pretty safe to remove it.

The removal of hair loss and beard may make traitorous virology harder if someone is trying to make a truly potent plague since it removes two buffing options for their disease. I don't have any good ideas for something different that could replace them but Virology barely sees traitorous use anyway, I doubt this is going to make things worse. But we probably should come up with at least one 'supporting' mid-level virus symptom to replace them down the line.

2022-11-25 08:30 UTC, SeigaSeiga commented
Oh, also it's gonna be easier to RNG roll for other desired symptoms in the respective tier of the removed ones. This won't be so bad for Voice Change [Level: 6, might make it easier to get positive symptoms], but for the other two they're _both_ level 4, which is a fairly big knock to the level 4 table, leaving only Deafness, Confusion, Dizziness and Sensory Restoration in that tier. Small pool.

2022-11-25 12:08 UTC, Jacquerel commented
If possible it would be better to have a replacement for each symptom _in this PR_ so that we aren't deleting the typepath, removing typepaths is our single most common cause of post-merge failures.

2022-12-14 17:32 UTC, Profakos requested changes
As Jacq said, please add replacements here, and figure out a way to make them not spawn without deleting the typepath. Setting their levels absurdly high should work?

2023-01-03 18:36 UTC, Profakos commented
Beard is being handled in #371, two more left.

2023-02-17 02:16 UTC, closed without merging